# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ch33o-XV6qXQv4L9q0h6LoFPVR5YTtJe
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install lxml_html_clean
!pip install newspaper3k

from newspaper import Article
import pandas as pd


real_path = '/content/drive/MyDrive/real_news_urls.txt'
fake_path = '/content/drive/MyDrive/fake_news_urls.txt'


with open(real_path, 'r') as f:
    real_urls = [line.strip() for line in f if line.strip()]

with open(fake_path, 'r') as f:
    fake_urls = [line.strip() for line in f if line.strip()]


data = []

def parse_articles(urls, label):
    for url in urls:
        try:
            article = Article(url, language='el')
            article.download()
            article.parse()
            if article.text.strip():
                text = article.title + "\n\n" + article.text
                data.append({'text': text, 'label': label})
        except Exception as e:
            print(f"Failed to parse {url}: {e}")


parse_articles(real_urls, 'real')
parse_articles(fake_urls, 'fake')


df = pd.DataFrame(data)
df.to_csv('/content/drive/MyDrive/parsed_articles.csv', index=False)
print("Αποθηκεύτηκαν τα άρθρα στο parsed_articles.csv")

print(df)

